services:
  auth:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - "50054:50051"
    working_dir: /app
    command: python -m app
    env_file:
      - .env_docker
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${dbname}
      DB_USER: ${dbUser}
      DB_PASSWORD: ${dbPassword}

volumes:
  pgdata:
