# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import datatransform_pb2 as datatransform__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in datatransform_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DataTransformStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Transform = channel.unary_unary(
                '/datatransform.DataTransform/Transform',
                request_serializer=datatransform__pb2.TransformRequest.SerializeToString,
                response_deserializer=datatransform__pb2.TransformResponse.FromString,
                _registered_method=True)
        self.TransformAggregate = channel.unary_unary(
                '/datatransform.DataTransform/TransformAggregate',
                request_serializer=datatransform__pb2.AggregateRequest.SerializeToString,
                response_deserializer=datatransform__pb2.AggregateResponse.FromString,
                _registered_method=True)


class DataTransformServicer:
    """Missing associated documentation comment in .proto file."""

    def Transform(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TransformAggregate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataTransformServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Transform': grpc.unary_unary_rpc_method_handler(
                    servicer.Transform,
                    request_deserializer=datatransform__pb2.TransformRequest.FromString,
                    response_serializer=datatransform__pb2.TransformResponse.SerializeToString,
            ),
            'TransformAggregate': grpc.unary_unary_rpc_method_handler(
                    servicer.TransformAggregate,
                    request_deserializer=datatransform__pb2.AggregateRequest.FromString,
                    response_serializer=datatransform__pb2.AggregateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'datatransform.DataTransform', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('datatransform.DataTransform', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DataTransform:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Transform(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/datatransform.DataTransform/Transform',
            datatransform__pb2.TransformRequest.SerializeToString,
            datatransform__pb2.TransformResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TransformAggregate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/datatransform.DataTransform/TransformAggregate',
            datatransform__pb2.AggregateRequest.SerializeToString,
            datatransform__pb2.AggregateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
