# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x04\x61uth\"1\n\x0b\x43redentials\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"O\n\rLoginResponse\x12\x13\n\x0b\x61\x63\x65ss_token\x18\x01 \x01(\t\x12\x15\n\rrefresh_token\x18\x02 \x01(\t\x12\x12\n\nexpires_at\x18\x03 \x01(\x03\"\'\n\x0eRefreshRequest\x12\x15\n\rrefresh_token\x18\x01 \x01(\t\"9\n\x0eRefresResponse\x12\x13\n\x0b\x61\x63\x65ss_token\x18\x01 \x01(\t\x12\x12\n\nexpires_at\x18\x02 \x01(\x03\"&\n\rLogoutRequest\x12\x15\n\rrefresh_token\x18\x01 \x01(\t\"\x10\n\x0eLogoutResponse2\xa8\x01\n\x04\x41uth\x12/\n\x05Login\x12\x11.auth.Credentials\x1a\x13.auth.LoginResponse\x12:\n\x0cRefreshToken\x12\x14.auth.RefreshRequest\x1a\x14.auth.RefresResponse\x12\x33\n\x06Logout\x12\x13.auth.LogoutRequest\x1a\x14.auth.LogoutResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREDENTIALS']._serialized_start=20
  _globals['_CREDENTIALS']._serialized_end=69
  _globals['_LOGINRESPONSE']._serialized_start=71
  _globals['_LOGINRESPONSE']._serialized_end=150
  _globals['_REFRESHREQUEST']._serialized_start=152
  _globals['_REFRESHREQUEST']._serialized_end=191
  _globals['_REFRESRESPONSE']._serialized_start=193
  _globals['_REFRESRESPONSE']._serialized_end=250
  _globals['_LOGOUTREQUEST']._serialized_start=252
  _globals['_LOGOUTREQUEST']._serialized_end=290
  _globals['_LOGOUTRESPONSE']._serialized_start=292
  _globals['_LOGOUTRESPONSE']._serialized_end=308
  _globals['_AUTH']._serialized_start=311
  _globals['_AUTH']._serialized_end=479
# @@protoc_insertion_point(module_scope)
