# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: datatransform.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'datatransform.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x64\x61tatransform.proto\x12\rdatatransform\"\x86\x01\n\x07Patient\x12\x12\n\npatient_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x12\n\nbirth_date\x18\x03 \x01(\t\x12\x0e\n\x06gender\x18\x04 \x01(\t\x12\x0c\n\x04\x63ity\x18\x05 \x01(\t\x12\r\n\x05state\x18\x06 \x01(\t\x12\x0b\n\x03\x63pf\x18\x07 \x01(\t\x12\x0b\n\x03\x63ns\x18\x08 \x01(\t\"\x87\x01\n\tEncounter\x12\x14\n\x0c\x65ncounter_id\x18\x01 \x01(\t\x12\x12\n\npatient_id\x18\x02 \x01(\t\x12\x12\n\nstart_date\x18\x03 \x01(\t\x12\x10\n\x08\x65nd_date\x18\x04 \x01(\t\x12\x16\n\x0e\x65ncounter_type\x18\x05 \x01(\t\x12\x12\n\ndepartment\x18\x06 \x01(\t\"\xb9\x01\n\rClinicalEvent\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\x12\x12\n\npatient_id\x18\x02 \x01(\t\x12\x14\n\x0c\x65ncounter_id\x18\x03 \x01(\t\x12\x12\n\nevent_type\x18\x04 \x01(\t\x12\x12\n\nevent_code\x18\x05 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x06 \x01(\t\x12\x12\n\nevent_date\x18\x07 \x01(\t\x12\r\n\x05value\x18\x08 \x01(\t\x12\x0c\n\x04unit\x18\t \x01(\t\"\xa0\x01\n\x10TransformRequest\x12\'\n\x07patient\x18\x01 \x01(\x0b\x32\x16.datatransform.Patient\x12,\n\nencounters\x18\x02 \x03(\x0b\x32\x18.datatransform.Encounter\x12\x35\n\x0f\x63linical_events\x18\x03 \x03(\x0b\x32\x1c.datatransform.ClinicalEvent\"-\n\x11TransformResponse\x12\x18\n\x10\x66hir_bundle_json\x18\x01 \x01(\t\"\x88\x01\n\x10\x41ggregateRequest\x12\x13\n\x0b\x63ohort_code\x18\x01 \x01(\t\x12(\n\x08patients\x18\x02 \x03(\x0b\x32\x16.datatransform.Patient\x12\x35\n\x0f\x63linical_events\x18\x03 \x03(\x0b\x32\x1c.datatransform.ClinicalEvent\"-\n\x11\x41ggregateResponse\x12\x18\n\x10\x66hir_bundle_json\x18\x01 \x01(\t2\xb8\x01\n\rDataTransform\x12N\n\tTransform\x12\x1f.datatransform.TransformRequest\x1a .datatransform.TransformResponse\x12W\n\x12TransformAggregate\x12\x1f.datatransform.AggregateRequest\x1a .datatransform.AggregateResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'datatransform_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PATIENT']._serialized_start=39
  _globals['_PATIENT']._serialized_end=173
  _globals['_ENCOUNTER']._serialized_start=176
  _globals['_ENCOUNTER']._serialized_end=311
  _globals['_CLINICALEVENT']._serialized_start=314
  _globals['_CLINICALEVENT']._serialized_end=499
  _globals['_TRANSFORMREQUEST']._serialized_start=502
  _globals['_TRANSFORMREQUEST']._serialized_end=662
  _globals['_TRANSFORMRESPONSE']._serialized_start=664
  _globals['_TRANSFORMRESPONSE']._serialized_end=709
  _globals['_AGGREGATEREQUEST']._serialized_start=712
  _globals['_AGGREGATEREQUEST']._serialized_end=848
  _globals['_AGGREGATERESPONSE']._serialized_start=850
  _globals['_AGGREGATERESPONSE']._serialized_end=895
  _globals['_DATATRANSFORM']._serialized_start=898
  _globals['_DATATRANSFORM']._serialized_end=1082
# @@protoc_insertion_point(module_scope)
