# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import patient_data_pb2 as patient__data__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in patient_data_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PatientDataServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HealthCheck = channel.unary_unary(
                '/patientdata.PatientDataService/HealthCheck',
                request_serializer=patient__data__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=patient__data__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.GetPatient = channel.unary_unary(
                '/patientdata.PatientDataService/GetPatient',
                request_serializer=patient__data__pb2.GetPatientRequest.SerializeToString,
                response_deserializer=patient__data__pb2.GetPatientResponse.FromString,
                _registered_method=True)
        self.SearchPatients = channel.unary_unary(
                '/patientdata.PatientDataService/SearchPatients',
                request_serializer=patient__data__pb2.SearchPatientsRequest.SerializeToString,
                response_deserializer=patient__data__pb2.SearchPatientsResponse.FromString,
                _registered_method=True)
        self.ListEncounters = channel.unary_unary(
                '/patientdata.PatientDataService/ListEncounters',
                request_serializer=patient__data__pb2.ListEncountersRequest.SerializeToString,
                response_deserializer=patient__data__pb2.ListEncountersResponse.FromString,
                _registered_method=True)
        self.ListClinicalEvents = channel.unary_unary(
                '/patientdata.PatientDataService/ListClinicalEvents',
                request_serializer=patient__data__pb2.ListClinicalEventsRequest.SerializeToString,
                response_deserializer=patient__data__pb2.ListClinicalEventsResponse.FromString,
                _registered_method=True)
        self.ListResearchProjects = channel.unary_unary(
                '/patientdata.PatientDataService/ListResearchProjects',
                request_serializer=patient__data__pb2.ListResearchProjectsRequest.SerializeToString,
                response_deserializer=patient__data__pb2.ListResearchProjectsResponse.FromString,
                _registered_method=True)
        self.GetCohortStats = channel.unary_unary(
                '/patientdata.PatientDataService/GetCohortStats',
                request_serializer=patient__data__pb2.GetCohortStatsRequest.SerializeToString,
                response_deserializer=patient__data__pb2.GetCohortStatsResponse.FromString,
                _registered_method=True)
        self.ListAnonymizedLabResults = channel.unary_unary(
                '/patientdata.PatientDataService/ListAnonymizedLabResults',
                request_serializer=patient__data__pb2.ListAnonymizedLabResultsRequest.SerializeToString,
                response_deserializer=patient__data__pb2.ListAnonymizedLabResultsResponse.FromString,
                _registered_method=True)


class PatientDataServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPatient(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchPatients(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListEncounters(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListClinicalEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListResearchProjects(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCohortStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAnonymizedLabResults(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PatientDataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=patient__data__pb2.HealthCheckRequest.FromString,
                    response_serializer=patient__data__pb2.HealthCheckResponse.SerializeToString,
            ),
            'GetPatient': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPatient,
                    request_deserializer=patient__data__pb2.GetPatientRequest.FromString,
                    response_serializer=patient__data__pb2.GetPatientResponse.SerializeToString,
            ),
            'SearchPatients': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchPatients,
                    request_deserializer=patient__data__pb2.SearchPatientsRequest.FromString,
                    response_serializer=patient__data__pb2.SearchPatientsResponse.SerializeToString,
            ),
            'ListEncounters': grpc.unary_unary_rpc_method_handler(
                    servicer.ListEncounters,
                    request_deserializer=patient__data__pb2.ListEncountersRequest.FromString,
                    response_serializer=patient__data__pb2.ListEncountersResponse.SerializeToString,
            ),
            'ListClinicalEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.ListClinicalEvents,
                    request_deserializer=patient__data__pb2.ListClinicalEventsRequest.FromString,
                    response_serializer=patient__data__pb2.ListClinicalEventsResponse.SerializeToString,
            ),
            'ListResearchProjects': grpc.unary_unary_rpc_method_handler(
                    servicer.ListResearchProjects,
                    request_deserializer=patient__data__pb2.ListResearchProjectsRequest.FromString,
                    response_serializer=patient__data__pb2.ListResearchProjectsResponse.SerializeToString,
            ),
            'GetCohortStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCohortStats,
                    request_deserializer=patient__data__pb2.GetCohortStatsRequest.FromString,
                    response_serializer=patient__data__pb2.GetCohortStatsResponse.SerializeToString,
            ),
            'ListAnonymizedLabResults': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAnonymizedLabResults,
                    request_deserializer=patient__data__pb2.ListAnonymizedLabResultsRequest.FromString,
                    response_serializer=patient__data__pb2.ListAnonymizedLabResultsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'patientdata.PatientDataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('patientdata.PatientDataService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PatientDataService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/patientdata.PatientDataService/HealthCheck',
            patient__data__pb2.HealthCheckRequest.SerializeToString,
            patient__data__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPatient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/patientdata.PatientDataService/GetPatient',
            patient__data__pb2.GetPatientRequest.SerializeToString,
            patient__data__pb2.GetPatientResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchPatients(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/patientdata.PatientDataService/SearchPatients',
            patient__data__pb2.SearchPatientsRequest.SerializeToString,
            patient__data__pb2.SearchPatientsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListEncounters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/patientdata.PatientDataService/ListEncounters',
            patient__data__pb2.ListEncountersRequest.SerializeToString,
            patient__data__pb2.ListEncountersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListClinicalEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/patientdata.PatientDataService/ListClinicalEvents',
            patient__data__pb2.ListClinicalEventsRequest.SerializeToString,
            patient__data__pb2.ListClinicalEventsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListResearchProjects(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/patientdata.PatientDataService/ListResearchProjects',
            patient__data__pb2.ListResearchProjectsRequest.SerializeToString,
            patient__data__pb2.ListResearchProjectsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCohortStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/patientdata.PatientDataService/GetCohortStats',
            patient__data__pb2.GetCohortStatsRequest.SerializeToString,
            patient__data__pb2.GetCohortStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAnonymizedLabResults(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/patientdata.PatientDataService/ListAnonymizedLabResults',
            patient__data__pb2.ListAnonymizedLabResultsRequest.SerializeToString,
            patient__data__pb2.ListAnonymizedLabResultsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
